model_name = "Qwen/QwQ-32B"
dataset = "justus27/rl-code-and-math"
batch_size = 16
tp = "auto"
max_model_len = 16_000

[sampling]
n = 16

[len_reward]
reward_type = "exact"
length_prompt_location = "instruction"
target_lengths = [2000, 4000, 6000, 8000, 10000]

[difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.1
max_solve_rate = 0.8