model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"
dataset = "justus27/rl-code-and-math"

batch_size = 8
tp = "auto"
max_model_len = 16000

[sampling]
n = 32

[difficulty_filtering]
solve_rate_field = "solve_rate_qwen_r1_distill_7b"
min_solve_rate = 0.0
max_solve_rate = 0.7