model_name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"  # Or another suitable base model
dataset = "preetammukherjee/sanskrit_morph_prakriya"
batch_size = 14 # Can be adjusted
dp = 1 # Default to 1, can be adjusted based on GPU availability in target environment
rollout_path = "sanskrit_rollout_ckpt" # Directory for model checkpoints for inference
output_path = "sanskrit_experience_data" # Directory where Parquet experience files will be written
clean_output_path = true
max_model_len = 512 # Adjust based on typical length of metadata string + Sanskrit word
task_type = "sanskrit_morph" # Custom field to identify the task

# Sampling parameters (can be tuned)
[sampling]
n = 1
temperature = 0.7
top_p = 1.0
# max_tokens = 64 # Max tokens for generated Sanskrit word, adjust as needed 