name: Style

on:
  push:
    branches:
      - main
  pull_request:
    # This will trigger the workflow for pull requests to any branch
    types: [opened, synchronize, reopened]

jobs:
  ruff:
    name: Run ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run ruff
        uses: astral-sh/ruff-action@v3
